language: dart
dart: 
  - stable
sudo: false
before_script:
 - chmod +x ./tool/travis.sh
 - chmod +x ./tool/publish.sh
 - pub get
script: ./tool/travis.sh
deploy:
  provider: script
  script: ./tool/publish.sh
  skip_cleanup: true
  on:
    branch: master
    dart: stable