name: epubz
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/FlafyDev/dart-epubz
issue_tracker: https://github.com/FlafyDev/dart-epubz
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ^3.1.6
  quiver: ^3.0.1+1
  xml: ^5.3.1
  image: ^3.0.8
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.7
  path: ^1.8.0
  pedantic: ^1.11.0
